#!/bin/bash
show_help() {
  echo "Usage: $(basename $0) <project_name>"
  echo "<project_name> is the name of the project you want to create"
  echo "  -h, --help     Display this help message"
  # Add more options and descriptions as needed
  exit 0
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  show_help
fi

if [[ -z "$1" ]]; then
  echo "Error: <project_name> is required."
  show_help
fi

mkdir $1
cd $1
mkdir src
mkdir include
mkdir scripts
mkdir test
touch src/$1.cpp
touch include/$1.hpp
touch scripts/main.cpp
touch test/main.cpp
cp ~/bin/files/CMakeLists.txt CMakeLists.txt
sed -i -e "s/\[project_name\]/$1/g" CMakeLists.txt
cp ~/bin/files/cpp_ignore .gitignore